#!/bin/sh

#+ Initiate workspaces:
bspc monitor -d main www irc foo bar

bspc config top_padding 14
bspc monitor -n :0

#+ Rules:
bspc config rule_command "$(which rule_command)"

rulc -a 'class=="Dwb"' 'desktop=^2 follow=on'
rulc -a 'class=="BSPWM_FRAME"' 'frame=on'




## Settings:
#+ focus
#bspc set history_aware_focus true
#bspc set focus_by_distance   false

#+ splitting
#bspc set split_ratio         0.50

#+ decoration
bspc config border_width     1
bspc config window_gap       13
#bspc set borderless_monocle  true
#bspc set gapless_monocle     true

#+ colors
bspc config focused_border_color        "#745e54"
bspc config presel_border_color		"#8eb0aa"

#+ stuff
bspc config focused_frame_opacity 0.20
bspc config normal_frame_opacity 0.00

sleep 2; panel &
