##Configure your zsh

##General
autoload -Uz compinit 
autoload promptinit
autoload colors
autoload -Uz prompt_special_chars

compinit
colors
promptinit
prompt_special_chars

setopt notify
setopt prompt_subst
setopt completealiases

##Comfort
zstyle :compinstall filename '/home/danny/.zshrc'
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

##History
zstyle ':completion:*:history-words' stop yes                                      
zstyle ':completion:*:history-words' remove-all-dups yes                           
zstyle ':completion:*:history-words' list false                                    
zstyle ':completion:*:history-words' menu yes                                      
zstyle ':completion::complete:*' use-cache 1

bindkey '\e[A' history-search-backward                                          
bindkey '\e[B' history-search-forward

##Stuff
export HISTSIZE=2000                                                            
export HISTFILE="$HOME/.zsh_history"                                            
export SAVEHIST=$HISTSIZE
export EDITOR=vim
export PAGER=less
export NNTPSERVER='nntp.flying-sheep.de'
#export NNTPSERVER='news.linuxfromscratch.org'
export COLORSCHEME='$HOME/.colors/bspwm.sheme'



 #PS1
# if [[ $(whoami) = root ]]; then
#	PROMPT='%{$fg[blue]%}┌─%{${reset_color}%}[ %{$fg_bold[red]%}%n%{${reset_color}%} ]%{$fg[blue]%}───%{${reset_color}%}[ %U%{$fg[magenta]%}%1~%{${reset_color}%}%u ]%{$fg[blue]%}
#└──╼%{${reset_color}%} '
#else
#        PROMPT='%{$fg[blue]%}┌─%{${reset_color}%}[ %{$fg[green]%}%n%{${reset_color}%} ]%{$fg[blue]%}───%{${reset_color}%}[ %U%{$fg[blue]%}%1~%{${reset_color}%}%u ]%{$fg[blue]%}
#└──╼%{${reset_color}%} '
#fi

if [[ $(whoami) = root ]] 
then
	PROMPT='%{$fg[red]%}─── %{${reset_color}%}'
	RPROMPT='%1~%'
else
	PROMPT='%{$fg[blue]%}─── %{${reset_colo}%}'
	RPROMPT='%1~%'
fi

PS2=' > '

##Aliase
alias rm='rm -v'
alias cp='cp -v'


alias abs='sudo abs'
alias systemctl='sudo systemctl'
alias pacman='sudo pacman'
alias pacman-optimize='sudo pacman-optimize'
alias pacsrc='sudo srcpac'
alias la='ls -laF --color=always | /home/danny/.bin/coloredls'
alias l='ls -lF --color=always --group-directories-first | /home/danny/.bin/coloredls'
alias cat="/home/danny/.bin/sh/cat"
alias cats='/usr/bin/cat'
alias ping='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/ping'
alias wget='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/wget'
alias df='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/df'
alias mpc='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/mpc'
alias make='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/make'
alias ip='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/ip'
alias lspci='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/lspci'
alias blkid='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/blkid'
alias acpi='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/acpi'
alias free='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/free'
alias ps='/usr/share/perl5/vendor_perl/auto/share/dist/Cope/ps'
alias spaceinvaders='sh .bin/sh/spaceinvaders.sh'
alias vi='vim'
alias pipes='sh /home/danny/.bin/sh/pipes.sh'
alias ..='cd ..'
alias cd='cd'
alias echo='echo'
alias lf='ls -fl | /home/danny/.bin/coloredls'
alias day='date +%A'


##Functions
function mkcd(){
mkdir -p "$1" && cd "$1"
}

function getbspwm() {
git clone https://github.com/baskerville/bspwm.git
}


function cdl() {
cd $1; l
}

function remindme(){
sleep $1; echo -e "\nZeitspanne ist vorüber\n"; mplayer ~/musik/Sabaton.mp3
}

function lsd(){
var1=$(ls -l | wc -l)
var2=$(ls -la | wc -l)
calc=$(echo "$var2-$var1-2" | bc -l)
echo "$calc dotfiles"
}

function reload() {
. $HOME/.zshrc
}

function chan() {
export Serv="$1"
export CHAN="$2"
}

function loadaur() {
wget $(aurquery $1 | awk '/URLPath:/ {print $2}')
}

function send() {
echo "$1" > $HOME/irc/$Serv/$CHAN/in
}

##Highlight stuff
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('su ' 'fg=white,bold,bg=blue')
ZSH_HIGHLIGHT_STYLES[builtin]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[commands]='fg=green'
ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
ZSH_HIGHLIGHT_STYLES[precomannds]='fg=green,underline'
ZSH_HIGHLIGHT_STYLES[assign]=none
ZSH_HIGHLIGHT_STYLES[path_approx]='fg=yellow'
